include theos/makefiles/common.mk

LIBRARY_NAME = searchcommandsdylibs anotherdylib
searchcommandsdylibs_FILES = searchcommandsdylibs.mm
searchcommandsdylibs_INSTALL_PATH = /var/mobile/Library/SearchCommands

anotherdylib_FILES = anotherdylib.mm
anotherdylib_FRAMEWORKS = UIKit
anotherdylib_INSTALL_PATH = /var/mobile/Library/SearchCommands

include $(THEOS_MAKE_PATH)/library.mk
