include theos/makefiles/common.mk

LIBRARY_NAME = date time sms mail call

date_FILES = date.mm
date_FRAMEWORKS = UIKit
date_INSTALL_PATH = /var/mobile/Library/SearchCommands/

time_FILES = time.mm
time_FRAMEWORKS = UIKit
time_INSTALL_PATH = /var/mobile/Library/SearchCommands/

sms_FILES = sms.mm
sms_FRAMEWORKS = UIKit
sms_INSTALL_PATH = /var/mobile/Library/SearchCommands/

mail_FILES = mail.mm
mail_FRAMEWORKS = UIKit
mail_INSTALL_PATH = /var/mobile/Library/SearchCommands/

include $(THEOS_MAKE_PATH)/library.mk
